#pragma once

#include <cstdint>
#include <optional>
#include <span>
#include <string>
#include <vector>

#include "zmq.hpp"
#include "spdlog/spdlog.h"

#include "api/channel.pb.h"
#include "api/node.pb.h"
#include "api/synapse.pb.h"
#include "api/query.pb.h"
#include "intan_rhd2132_constants.h"
#include "intan_rhd2132_registers.h"
#include "scifi-peripheral-sdk/axon/protocol.h"
#include "scifi-peripheral-sdk/record_plugin.h"
#include "scifi-peripheral-sdk/scifi/status.h"
#include "scifi-peripheral-sdk/scifi/time.h"

namespace intan_rhd2132 {

class IntanRhd2132Peripheral
    : public scifi::plugin::RecordPluginWithLimits<IntanRhd2132Peripheral> {
 public:
  // Hardware-limits contract. The SDK reads these at construction time and
  // forwards them into RecordPlugin.
  SCIFI_RECORD_PLUGIN_LIMITS(
      /*max_sample_rate  =*/ MAX_SAMPLE_RATE,
      /*max_bit_width    =*/ MAX_BIT_WIDTH,
      /*max_gain         =*/ MAX_GAIN,
      /*max_channel_count=*/ CHANNEL_COUNT);

  // No constructor body needed — inherit RecordPluginWithLimits's 5-arg ctor.
  using RecordPluginWithLimits::RecordPluginWithLimits;

  // ~IntanRhd2132Peripheral defaults — RecordPlugin owns the sockets and they
  // close themselves when destructed.

  [[nodiscard]] synapse::Peripheral to_proto() const override;
  [[nodiscard]] float get_lsb(float hp_corner_hz, float lp_corner_hz) const override;

  [[nodiscard]] synapse::QueryResponse self_test(const synapse::SelfTestQuery& query) override;

  [[nodiscard]] const std::optional<std::string> validate_ephys_config(
      const synapse::BroadbandSourceConfig& config) const override;

  [[nodiscard]] scifi::Status get_impedance(uint32_t electrode_id, float stim_freq, float& mag,
                                            float& phase) override;

  [[nodiscard]] scifi::Status configure_sample_rate(double desired_sample_rate,
                                                    double& actual_sample_rate) override;

  [[nodiscard]] bool set_fpga_clk_freq_hz(uint32_t fpga_clk_freq_hz) override {
    if (intan_rhd2132::FPGA_CLK_FREQS_HZ.count(fpga_clk_freq_hz) == 0) {
      return false;
    }
    fpga_clk_freq_hz_ = fpga_clk_freq_hz;
    registers_.set_fpga_clk_freq_hz(fpga_clk_freq_hz);
    return true;
  }

 protected:
  [[nodiscard]] scifi::Status start_recording_impl(uint32_t sample_rate, uint32_t bit_width,
                                                   std::vector<synapse::Channel> channels,
                                                   float gain, float hp_corner,
                                                   float lp_corner,
                                                   uint32_t& actual_sample_rate) override;
  [[nodiscard]] scifi::Status stop_recording_impl() override;

  // One SPI_LOOP_RESPONSE packet = one frame. Each payload word holds a single
  // 16-bit sample in its low half: 0x0000_RRRR. Walks channels_enabled_ words
  // into frame_buffer_ and returns a span over it.
  [[nodiscard]] std::span<const uint16_t> parse_frame_payload(
      std::span<const uint32_t> payload_words) override;

  [[nodiscard]] scifi::Status configure_bit_width(uint16_t bit_width) override;
  [[nodiscard]] scifi::Status configure_channels(
      const std::vector<synapse::Channel>& channels) override;

 private:
  static constexpr int SPI_RESPONSE_TIMEOUT_MS = 1000;
  static constexpr int ZMQ_RECV_TIMEOUT_MS = 500;

  [[nodiscard]] scifi::Status push_registers_();
  [[nodiscard]] scifi::Status pull_registers_(bool verbose = false);
  [[nodiscard]] scifi::Status verify_chip_identity_();
  [[nodiscard]] scifi::Status calibrate_adc_();
  [[nodiscard]] std::vector<uint32_t> build_acquisition_loop_() const;

  // Capture N batched SPI_LOOP_RESPONSE packets and extract the CONVERT samples at the
  // payload indices generated by the timed impedance loop.
  [[nodiscard]] scifi::Status capture_impedance_samples_(
      uint32_t loop_len_words, const std::vector<uint32_t>& convert_payload_indices,
      uint32_t num_iterations, std::vector<double>& samples);

  IntanRhd2132Registers registers_;

  uint32_t channels_enabled_ = 0;

  // Scratch buffer for parse_frame_payload. Sized to the chip's hardware
  // channel count (worst case). Written once per packet, read by the SDK's
  // read_frames before the next packet arrives — single-threaded by contract.
  uint16_t frame_buffer_[CHANNEL_COUNT] = {};
};

}  // namespace intan_rhd2132
