#pragma once

#include <atomic>
#include <memory>
#include <string>
#include <vector>

#include "zmq.hpp"
#include "spdlog/spdlog.h"

#include "api/channel.pb.h"
#include "api/node.pb.h"
#include "api/synapse.pb.h"
#include "api/query.pb.h"
#include "intan_rhd2132_constants.h"
#include "intan_rhd2132_registers.h"
#include "scifi-peripheral-sdk/axon/io.h"
#include "scifi-peripheral-sdk/axon/protocol.h"
#include "scifi-peripheral-sdk/axon/record_peripheral.h"
#include "scifi-peripheral-sdk/axon/subscription.h"
#include "scifi-peripheral-sdk/scifi/status.h"
#include "scifi-peripheral-sdk/scifi/time.h"

namespace chips {
namespace intan_rhd2132 {

class IntanRhd2132Peripheral : public axon::RecordPeripheral {
 public:
  IntanRhd2132Peripheral(uint32_t periph_id, uint32_t peripheral_addr, zmq::context_t& ctx,
                         const std::string& axon_tx_endpoint, const std::string& axon_rx_endpoint);
  explicit IntanRhd2132Peripheral(uint32_t periph_id, uint32_t peripheral_addr,
                                  zmq::context_t& ctx);

  ~IntanRhd2132Peripheral();

  [[nodiscard]] scifi::Status start_recording(uint32_t sample_rate, uint32_t bit_width,
                                              std::vector<synapse::Channel> channels, float gain,
                                              float hp_corner = -1, float lp_corner = -1) override;
  [[nodiscard]] scifi::Status stop_recording() override;

  [[nodiscard]] std::vector<axon::MyelinFrame> read_frames(uint32_t num_frames) override;
  axon::ChannelData read(uint32_t num_frames) override;

  [[nodiscard]] synapse::Peripheral to_proto() const override;
  [[nodiscard]] float get_lsb(float hp_corner_hz, float lp_corner_hz) const override;

  [[nodiscard]] synapse::QueryResponse self_test(const synapse::SelfTestQuery& query) override;

  [[nodiscard]] const std::optional<std::string> validate_ephys_config(
      const synapse::BroadbandSourceConfig& config) const override;
  [[nodiscard]] const std::optional<std::string> validate_channels(
      const std::vector<synapse::Channel>& channels) const override;

  [[nodiscard]] scifi::Status get_impedance(uint32_t electrode_id, float stim_freq, float& mag,
                                            float& phase) override;

  [[nodiscard]] scifi::Status configure_sample_rate(double desired_sample_rate,
                                                    double& actual_sample_rate) override;

  [[nodiscard]] bool set_fpga_clk_freq_hz(uint32_t fpga_clk_freq_hz) override {
    if (intan_rhd2132::FPGA_CLK_FREQS_HZ.count(fpga_clk_freq_hz) == 0) {
      return false;
    }
    fpga_clk_freq_hz_ = fpga_clk_freq_hz;
    registers_.set_fpga_clk_freq_hz(fpga_clk_freq_hz);
    return true;
  }

 protected:
  [[nodiscard]] scifi::Status configure_bit_width(uint16_t bit_width) override;
  [[nodiscard]] scifi::Status configure_channels(
      const std::vector<synapse::Channel>& channels) override;

 private:
  static constexpr int SPI_RESPONSE_TIMEOUT_MS = 1000;
  static constexpr int ZMQ_RECV_TIMEOUT_MS = 500;

  [[nodiscard]] scifi::Status push_registers_();
  [[nodiscard]] scifi::Status pull_registers_(bool verbose = false);
  [[nodiscard]] scifi::Status verify_chip_identity_();
  [[nodiscard]] scifi::Status calibrate_adc_();
  [[nodiscard]] std::vector<uint32_t> build_acquisition_loop_() const;
  int clear_rx_socket_();

  // Capture N batched SPI_LOOP_RESPONSE packets and extract the CONVERT samples at the
  // payload indices generated by the timed impedance loop.
  [[nodiscard]] scifi::Status capture_impedance_samples_(
      uint32_t loop_len_words, const std::vector<uint32_t>& convert_payload_indices,
      uint32_t num_iterations, std::vector<double>& samples);

  IntanRhd2132Registers registers_;

  zmq::context_t& context_;
  zmq::socket_t axon_tx_sock_;
  zmq::socket_t axon_rx_sock_;
  std::atomic<bool> read_enable_ = false;
  const uint32_t peripheral_addr_;

  uint32_t channels_enabled_ = 0;
  uint64_t samples_delivered_ = 0;
  uint64_t dropped_packets_ = 0;

  // Drop detection: gateware emits one SPI_LOOP_RESPONSE per loop iteration (= one frame)
  // with a monotonically increasing seq_num. We just verify each new seq_num is the previous + 1.
  uint64_t last_seq_num_ = 0;
  bool first_frame_received_ = false;

  const std::string axon_tx_endpoint_ = axon::TX_SOCKET;
  const std::string axon_rx_endpoint_ = axon::RX_SOCKET;

  // Active SPI_LOOP_RESPONSE subscription owned by the start_recording →
  // stop_recording lifecycle. Held by unique_ptr because AxonRxSubscription
  // is non-movable (it stores a reference to axon_rx_sock_) and we need to
  // reset it at stop time to trigger the disconnect+unsubscribe in the dtor.
  std::unique_ptr<axon::AxonRxSubscription> loop_subscription_;

  uint16_t frame_buffer_[CHANNEL_COUNT] = {};
};

}  // namespace intan_rhd2132
}  // namespace chips
